### ISSUE TITLE
Drop down and right click menus on TexMaker 4.2 on Mac OS X not placed correctly

### ISSUE THREAD

**Issue by GoogleCodeExporter** [n370/texmaker#1287]
```
My system: Mac OS X Mavericks on a retina display MacBook Pro

The drop down menu that is supposed to appear when switching from one TeX file 
to the next shows up way too high on the screen.  Also, the menus that are 
supposed to appear when right clicking on the TeX source window or the PDF 
window appear too high.


```

Original issue reported on code.google.com by `jasonp...@gmail.com` on 5 May 2014 at 5:38
- Merged into: #1283

**Comment by alex2143** [comment]
Issue persists in TexMaker 4.5 on macOS Sierra, with 1440x900 main display and 2560x1440 secondary display (running it on the secondary display - menu placement is fine on the main display, both with the secondary display connected and not connected).

My hypothesis is that the offset from the top of the screen is calculated wrong, since the distance from the place where it SHOULD be and the place where it ACTUALLY appears, seems constant.
![screen shot 2017-05-30 at 10 10 33](https://cloud.githubusercontent.com/assets/11630755/26574065/45d3dffe-4520-11e7-9c3e-23f317b57f11.png)

If the window is maximized, the menu can fall off the screen.
(not sure if this is the right place to post - if so, feel free to correct me. Seemed to be the exact same issue as the OP, so thought I'd chime in)
